---
title: "Lecture 4"
subtitle: "Containers & Lambda"
author: "{{< var instructor.name >}}"
institute:
- "{{< var university.name >}}"
- "{{< var course.semester >}}"
format:
  revealjs:
    slide-number: true
    show-slide-number: print
    theme: custom.scss
    transition: fade
    background-transition: fade
    highlight-style: ayu-mirage
    code-copy: true
---

## Agenda and Goals for Today

:::: {.columns}
::: {.column width="50%"}

### Lecture

* Docker containers
    * Background and concepts
    * Syntax and commands
    * Examples

* Lambda/microservices
    * Background and concepts
    * Syntax and commands
    * Examples

:::

::: {.column width="50%"}

### Lab

- Lambda service exploration
- Cloud9 Setup
- Docker Container exploration in Cloud9

:::
::::

## Logistics and Review

:::: {.columns}
::: {.column width="50%"}

### Deadlines

- ~~Assignment 1: Python Skills **Due Sept 5 11:59pm**~~
- ~~Lab 2: Cloud Tooling **Due Sept 5 6pm**~~
- ~~Assignment 2: Shell & Linux **Due Sept 11 11:59pm**~~
- ~~Lab 3: Parallel Computing **Due Sept 12 6pm**~~
- Assignment 3: Parallelization **Due Sept 18 11:59pm**
- Lab 4: Docker and Lambda **Due Sept 19 6pm**
- Assignment 4: Containers **Due Sept 25 11:59pm**
- Lab 5: DuckDB & Polars **Due Sept 26 6pm**

:::
::: {.column width="50%"}

### Look back and ahead

* Continue to use Slack for questions!
* Parallelization in Python
* Concepts of `map` and `reduce`
* Choosing when to re-factor/optimize code for scalability
* **Questions on Assignment 3: Parallelization?**

:::
::::

{{< include docker/_docker.qmd >}}
{{< include microservices/_microservices.qmd >}}
